if Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.0')
  # Mixing Module#prepend with alias_method can sometimes lead to infinite
  # mutual recursion, so this is to test that it doesn't happen.
  mod = Module.new do
    def execute(args = nil)
      puts 'In module prepended to Rake::Task'
      super
    end
  end
  Rake::Task.send(:prepend, mod)
end

require "bugsnag/integrations/rake"

namespace :test do
  desc "used by integration_spec to test that Bugsnag::Middleware::Rake runs properly"
  task :crash do
    port = ENV['BUGSNAG_TEST_SERVER_PORT']
    Bugsnag.configure do |config|
      config.endpoint = "http://localhost:#{port}"
      config.api_key = "0" * 32
    end

    raise
  end
end
