source 'https://rubygems.org'

gem 'rake', '~> 12.3.0'

gem 'rails', '3.2.22.5'

gem 'nokogiri', '1.6.8'

gem 'sqlite3', '< 1.4'

gem 'jquery-rails'

gem 'bugsnag', path: '/bugsnag'

gem 'rack-cache', '~> 1.9.0'

gem "warden"
