source 'https://rubygems.org'

gem 'rake', '~> 12.3.0'

gem 'rails', '3.2.22.5'

gem 'nokogiri', '1.6.8'

gem 'sqlite3', '< 1.4'

gem 'jquery-rails'

gem 'bugsnag', path: '/bugsnag'

gem 'rack-cache', '~> 1.9.0'

gem "warden"

# Install a compatible Loofah version on Ruby <2.5
gem 'loofah', '2.20.0' if RUBY_VERSION < '2.5'

# Install a compatible Thor version on Ruby <2.6
gem 'thor', '<1.3.0' if RUBY_VERSION < '2.6'
