source 'https://rubygems.org'

gem 'bugsnag', path: '/bugsnag'
gem 'mailman'
gem 'hitimes', '~> 1.2.6'
gem 'i18n', '~> 0.9.5'
gem 'rb-inotify', '0.9.8'
gem 'maildir', '~> 2.1.0'
gem 'mail', '~> 2.7.1'
gem 'activesupport', '~> 3.2'
gem 'rack', '~> 1.6.11'

# Install a compatible FFI version on Ruby <2.3
gem 'ffi', '< 1.13.0' if RUBY_VERSION < '2.3.0'

# Install a compatible mini_mime version on Ruby <2.6
gem 'mini_mime', '< 1.1.4' if RUBY_VERSION < '2.6.0'
