source 'https://rubygems.org'

gem 'bugsnag', path: '../../'

gem 'rack', '~> 2.2'
gem 'redcarpet'

if Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('3.0.0')
  gem 'webrick', '~> 1.9.0'
end

if Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('4.0.0')
  gem 'ostruct', '~> 0.6.0'
end
