module Bugsnag::Breadcrumbs
  MAX_MESSAGE_LENGTH = 30

  ERROR_BREADCRUMB_TYPE = "error"
  MANUAL_BREADCRUMB_TYPE = "manual"
  NAVIGATION_BREADCRUMB_TYPE = "navigation"
  REQUEST_BREADCRUMB_TYPE = "request"
  PROCESS_BREADCRUMB_TYPE = "process"
  LOG_BREADCRUMB_TYPE = "log"
  USER_BREADCRUMB_TYPE = "user"
  STATE_BREADCRUMB_TYPE = "state"

  VALID_BREADCRUMB_TYPES = [
    ERROR_BREADCRUMB_TYPE,
    MANUAL_BREADCRUMB_TYPE,
    NAVIGATION_BREADCRUMB_TYPE,
    REQUEST_BREADCRUMB_TYPE,
    PROCESS_BREADCRUMB_TYPE,
    LOG_BREADCRUMB_TYPE,
    USER_BREADCRUMB_TYPE,
    STATE_BREADCRUMB_TYPE,
  ]
end