# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative 'config/application'

Rails.application.load_tasks

namespace :delayed_job_tests do
  task :fail_with_args do
    run_delayed_job_test('"TestModel.delay.fail_with_args(\"Test\")"')
  end

  task :notify_with_args do
    run_delayed_job_test('"TestModel.delay.notify_with_args(\"Test\")"')
  end

  task :report_context do
    run_delayed_job_test('"Delayed::Job.enqueue TestReportContextJob.new"')
  end
end

def run_delayed_job_test(command)
  # queue the job with rails' runner
  system("rails runner #{command}")

  # run the queued jobs and exit
  system("rake jobs:workoff")
end
